name: Deploy V2Ray Worker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Worker
        run: |
          # Install dependencies, configure worker and run
